-- MANUAL STEP — do not execute via db push.
-- pg_cron requires the extension to be enabled first in the Supabase Dashboard.
--
-- To schedule the daily FSRS notifier:
--   1. Dashboard → Extensions → enable pg_cron and pg_net
--   2. Run in SQL Editor (replace <YOUR_SERVICE_ROLE_KEY>):
--
-- select cron.schedule(
--   'daily-fsrs-reminder',
--   '0 8 * * *',
--   $$
--   select net.http_post(
--     url     := 'https://xborpnxbdvstiabtevix.supabase.co/functions/v1/fsrs-notifier',
--     headers := jsonb_build_object(
--       'Content-Type',  'application/json',
--       'Authorization', 'Bearer <YOUR_SERVICE_ROLE_KEY>'
--     ),
--     body    := '{}'::jsonb
--   ) as request_id;
--   $$
-- );
--
-- Alternatively: Edge Functions → fsrs-notifier → Schedules → Add → 0 8 * * *

SELECT 1; -- no-op placeholder so db push records this migration as applied
